--DF_FUNDAMENTALS_H_UPDATE
DELETE FROM DF_KPI_H WHERE LOAD_DATE IN (
SeLECT LOAD_DATE
FROM DF_QUOTE_TABLE);

INSERT INTO DF_KPI_H
	
 SELECT 
	T1.TICKER AS TICKER
,	T1.TARGET_EST_1Y AS TARGET_EST_1Y
,	T1.WEEK_RANGE_52 AS WEEK_RANGE_52
,	T1.ASK AS ASK
,	T1.AVG_VOLUME AS AVG_VOLUME
,	T1.BETA AS BETA
,	T1.BID AS BID
,	T1.DAYS_RANGE AS DAYS_RANGE
,	T1.EPS AS EPS
,	T1.EARNINGS_DATE AS EARNINGS_DATE
,	T1.EXDIVIDEND_DATE AS EXDIVIDEND_DATE
,	T1.FORWARD_DIVIDEND_YIELD AS FORWARD_DIVIDEND_YIELD
,	T1.MARKET_CAP AS MARKET_CAP
,	T1.OPEN AS OPEN
,	T1.PE_RATIO AS PE_RATIO
,	T1.PREVIOUS_CLOSE AS PREVIOUS_CLOSE
,	T1.QUOTE_PRICE AS QUOTE_PRICE
,	T1.VOLUME AS VOLUME
,	T2.CURRENT_QTR AS 	GROWTH_EST_CURRENT_QTR
,	T2.NEXT_QTR AS 	GROWTH_EST_NEXT_QTR
,	T2.CURRENT_YEAR AS 	GROWTH_EST_CURRENT_YEAR
,	T2.NEXT_YEAR AS 	GROWTH_EST_NEXT_YEAR
,	T2.NEXT_5_YEARS AS 	GROWTH_EST_NEXT_5_YEARS
,	T2.PAST_5_YEARS AS 	GROWTH_EST_PAST_5_YEARS
,	T3A.NO_OF_ANALYSTS AS 	REVENUE_EST_CQ_NO_OF_ANALYSTS
,	T3A.AVG_ESTIMATE AS 	REVENUE_EST_CQ_AVG_ESTIMATE
,	T3A.LOW_ESTIMATE AS 	REVENUE_EST_CQ_LOW_ESTIMATE
,	T3A.HIGH_ESTIMATE AS 	REVENUE_EST_CQ_HIGH_ESTIMATE
,	T3A.YEAR_AGO_SALES AS 	REVENUE_EST_CQ_YEAR_AGO_SALES
,	T3A.SALES_GROWTH AS 	REVENUE_EST_CQ_SALES_GROWTH
,	T3B.NO_OF_ANALYSTS AS 	REVENUE_EST_NQ_NO_OF_ANALYSTS
,	T3B.AVG_ESTIMATE AS 	REVENUE_EST_NQ_AVG_ESTIMATE
,	T3B.LOW_ESTIMATE AS 	REVENUE_EST_NQ_LOW_ESTIMATE
,	T3B.HIGH_ESTIMATE AS 	REVENUE_EST_NQ_HIGH_ESTIMATE
,	T3B.YEAR_AGO_SALES AS 	REVENUE_EST_NQ_YEAR_AGO_SALES
,	T3B.SALES_GROWTH AS 	REVENUE_EST_NQ_SALES_GROWTH
,	T3C.NO_OF_ANALYSTS AS 	REVENUE_EST_CY_NO_OF_ANALYSTS
,	T3C.AVG_ESTIMATE AS 	REVENUE_EST_CY_AVG_ESTIMATE
,	T3C.LOW_ESTIMATE AS 	REVENUE_EST_CY_LOW_ESTIMATE
,	T3C.HIGH_ESTIMATE AS 	REVENUE_EST_CY_HIGH_ESTIMATE
,	T3C.YEAR_AGO_SALES AS 	REVENUE_EST_CY_YEAR_AGO_SALES
,	T3C.SALES_GROWTH AS 	REVENUE_EST_CY_SALES_GROWTH
,	T3D.NO_OF_ANALYSTS AS 	REVENUE_EST_NY_NO_OF_ANALYSTS
,	T3D.AVG_ESTIMATE AS 	REVENUE_EST_NY_AVG_ESTIMATE
,	T3D.LOW_ESTIMATE AS 	REVENUE_EST_NY_LOW_ESTIMATE
,	T3D.HIGH_ESTIMATE AS 	REVENUE_EST_NY_HIGH_ESTIMATE
,	T3D.YEAR_AGO_SALES AS 	REVENUE_EST_NY_YEAR_AGO_SALES
,	T3D.SALES_GROWTH AS 	REVENUE_EST_NY_SALES_GROWTH
,	T4A.NO_OF_ANALYSTS AS 	EARNINGS_EST_CQ_NO_OF_ANALYSTS
,	T4A.AVG_ESTIMATE AS 	EARNINGS_EST_CQ_AVG_ESTIMATE
,	T4A.LOW_ESTIMATE AS 	EARNINGS_EST_CQ_LOW_ESTIMATE
,	T4A.HIGH_ESTIMATE AS 	EARNINGS_EST_CQ_HIGH_ESTIMATE
,	T4A.YEAR_AGO_EPS AS 	EARNINGS_EST_CQ_YEAR_AGO_EPS
,	T4B.NO_OF_ANALYSTS AS 	EARNINGS_EST_NQ_NO_OF_ANALYSTS
,	T4B.AVG_ESTIMATE AS 	EARNINGS_EST_NQ_AVG_ESTIMATE
,	T4B.LOW_ESTIMATE AS 	EARNINGS_EST_NQ_LOW_ESTIMATE
,	T4B.HIGH_ESTIMATE AS 	EARNINGS_EST_NQ_HIGH_ESTIMATE
,	T4B.YEAR_AGO_EPS AS 	EARNINGS_EST_NQ_YEAR_AGO_EPS
,	T4C.NO_OF_ANALYSTS AS 	EARNINGS_EST_CY_NO_OF_ANALYSTS
,	T4C.AVG_ESTIMATE AS 	EARNINGS_EST_CY_AVG_ESTIMATE
,	T4C.LOW_ESTIMATE AS 	EARNINGS_EST_CY_LOW_ESTIMATE
,	T4C.HIGH_ESTIMATE AS 	EARNINGS_EST_CY_HIGH_ESTIMATE
,	T4C.YEAR_AGO_EPS AS 	EARNINGS_EST_CY_YEAR_AGO_EPS
,	T4D.NO_OF_ANALYSTS AS 	EARNINGS_EST_NY_NO_OF_ANALYSTS
,	T4D.AVG_ESTIMATE AS 	EARNINGS_EST_NY_AVG_ESTIMATE
,	T4D.LOW_ESTIMATE AS 	EARNINGS_EST_NY_LOW_ESTIMATE
,	T4D.HIGH_ESTIMATE AS 	EARNINGS_EST_NY_HIGH_ESTIMATE
,	T4D.YEAR_AGO_EPS AS 	EARNINGS_EST_NY_YEAR_AGO_EPS
,	T5.EPS_TREND AS EPS_TREND
,	T5.CURRENT_QTR AS CURRENT_QTR
,	T5.NEXT_QTR AS NEXT_QTR
,	T5.CURRENT_YEAR AS CURRENT_YEAR
,	T5.NEXT_YEAR AS NEXT_YEAR
,	T6.REPORT_PERIOD-9 AS 	LATEST_REPORT_PERIOD	
,	T6.EPS_EST AS EPS_EST
,	T6.EPS_ACTUAL AS EPS_ACTUAL
,	T6.DIFFERENCE AS DIFFERENCE
,	T6.SURPRISE AS SURPRISE
,T1.LOAD_DATE
 FROM DF_QUOTE_TABLE AS T1
 LEFT JOIN DF_GROWTH_EST AS T2 ON T1.TICKER=T2.TICKER  AND T2.SECTOR  = LOWER(T2.TICKER )
 
  LEFT JOIN DF_REVENUE_EST AS T3A ON T1.TICKER=T3A.TICKER  AND T3A.REPORT_PERIOD LIKE LOWER('%CURRENT QTR%')
  LEFT JOIN DF_REVENUE_EST AS T3B ON T1.TICKER=T3B.TICKER  AND T3B.REPORT_PERIOD LIKE LOWER( '%NEXT QTR%')
  LEFT JOIN DF_REVENUE_EST AS T3C ON T1.TICKER=T3C.TICKER  AND T3C.REPORT_PERIOD LIKE LOWER(  '%CURRENT YEAR%')
  LEFT JOIN DF_REVENUE_EST AS T3D ON T1.TICKER=T3D.TICKER  AND T3D.REPORT_PERIOD LIKE LOWER(  '%NEXT YEAR%')
  
  LEFT JOIN DF_EARNINGS_EST AS T4A ON T1.TICKER=T4A.TICKER  AND T4A.REPORT_PERIOD LIKE LOWER('%CURRENT QTR%')
  LEFT JOIN DF_EARNINGS_EST AS T4B ON T1.TICKER=T4B.TICKER  AND T4B.REPORT_PERIOD LIKE LOWER('%NEXT QTR%')
  LEFT JOIN DF_EARNINGS_EST AS T4C ON T1.TICKER=T4C.TICKER  AND T4C.REPORT_PERIOD LIKE LOWER('%CURRENT YEAR%')
  LEFT JOIN DF_EARNINGS_EST AS T4D ON T1.TICKER=T4D.TICKER  AND T4D.REPORT_PERIOD LIKE LOWER('%NEXT YEAR%')
  LEFT JOIN DF_EPS_TREND AS T5 ON T1.TICKER=T5.TICKER  AND T5.EPS_TREND LIKE LOWER('%CURRENT ESTIMATE%')
  
  LEFT JOIN DF_EARNINGS_HIST AS T6 ON T1.TICKER=T6.TICKER  AND  T6.REPORT_PERIOD = (SELECT MAX (T6A.REPORT_PERIOD )
																				 FROM DF_EARNINGS_HIST AS  T6A
																				WHERE T6A.TICKER=T6.TICKER   )
 
 ;