
/*
Created Main table FUNDAMENTALS_HISTORIC
*/

DROP TABLE IF EXISTS FUNDAMENTALS_HISTORIC;

CREATE TABLE FUNDAMENTALS_HISTORIC(

    FUNDAMENTAL_ID INT
    ,TICKER VARCHAR(7)
    ,VALUE DECIMAL(12,4)
    ,YEAR INT
    ,LOAD_DATE DATE );


/*
Created REF table ID  BREAKDOWN_ID
*/

DROP TABLE IF EXISTS FUNDAMENTAL_ID;

CREATE TABLE FUNDAMENTAL_ID(
FUNDAMENTAL_ID INT
,FUNDAMENTAL_NAME VARCHAR (50)
);

