
DROP TABLE IF EXISTS DF_BUY_SELL_FLAG_2;
CREATE TABLE DF_BUY_SELL_FLAG_2  AS 

SELECT 
T1.	TICKER
,T1. PRICE_DATE
,T1. CLOSE_ADJ_PRICE
,T1. MA_10_BS_FLAG
,T1. MACD_BS_FLAG
,T1. SMI_BS_FLAG
,T1. ALL_BS_SUM
,T1. SEQ_EVENT
,T1. LOAD_DATE
FROM DF_BUY_SELL_FLAG T1
WHERE  1=1
--AND TICKER  IN ('LOGI', 'AMZN', 'TPL' , 'DQ' )
AND T1. PRICE_DATE  = (SELECT  MAX (T1A. PRICE_DATE)
						FROM DF_BUY_SELL_FLAG AS T1A
						WHERE  T1A. PRICE_DATE <=  CURRENT_DATE 
						AND T1.TICKER = T1A.TICKER);
				
				




-- ADD NEDED COLUMNS 
ALTER TABLE DF_BUY_SELL_FLAG_2  

ADD ALL_BS_SUM_DB INT
,ADD BS_FLAG  TEXT
,ADD DIFF_PRICE_PRC NUMERIC (10,6)
,ADD BS_FLAG_TRENT_DAYS_IN INT

,ADD Z_RANK	TEXT
,ADD Z_RANK_NUM INT 
,ADD Z_SECTOR_CLASS	TEXT
,ADD Z_INDUSTRY_RANK	TEXT
,ADD Z_EXP_GROWTH	DECIMAL (10,2)
,ADD Z_LOAD_DATE	DATE

,ADD Z_RANK_LB TEXT
,ADD Z_RANK_LB_NUM INT
,ADD Z_LOAD_DATE_LB DATE

,ADD Y_RANK	TEXT
,ADD Y_RANK_NUM INT 
,ADD Y_PRICE_1Y_EST	DECIMAL (10,2)
,ADD Y_LOAD_DATE	DATE


,ADD Y_RANK_LB TEXT
,ADD Y_RANK_LB_NUM INT
,ADD Y_LOAD_DATE_LB  DATE

,ADD REC_RANK TEXT
,ADD REC_RANK_IND TEXT
,ADD REC_RANK_NUM INT 
,ADD REC_VAR_ACTUAL	INT DEFAULT 0

,ADD REC_RANK_LB_NUM INT    

,ADD Z_VAR_ACTUAL_DAYSDIFF INT       
,ADD Y_VAR_ACTUAL_DAYSDIFF INT       
,ADD REC_VAR_ACTUAL_DAYSDIFF INT       
;



 ---BUY SELL FLAGS  AND CLOSE PRICE UPDATES STIKER_PRICE IF IT IS MORE RECENT 
 ---DAILY UPDATED WILL BE FROM THIS UPDATED
UPDATE DF_BUY_SELL_FLAG_2 T1
SET
    ALL_BS_SUM_DB	=	T2.	ALL_BS_SUM_DB
    ,BS_FLAG = T2.BS_FLAG
    ,DIFF_PRICE_PRC = T2.DIFF_PRICE_PRC
    
FROM (

            SELECT 
            T1.TICKER
            ,T1.PRICE_DATE
            ,T2.PRICE_DATE  AS  DATE_DB
            ,T1.ALL_BS_SUM      
            ,T2.ALL_BS_SUM    AS  ALL_BS_SUM_DB
            , CASE WHEN T1.ALL_BS_SUM = 3 THEN  'BUY ++'
            WHEN T1.ALL_BS_SUM = -3 THEN  'SELL ++'
            WHEN T1.ALL_BS_SUM > 0 AND T2.ALL_BS_SUM  < T1.ALL_BS_SUM  THEN  'BUY +'
            WHEN T1.ALL_BS_SUM < 0 AND T2.ALL_BS_SUM  > T1.ALL_BS_SUM  THEN  'SELL +'
            WHEN T1.ALL_BS_SUM > 0 AND T2.ALL_BS_SUM  >= T1.ALL_BS_SUM  THEN  'BUY -'
            WHEN T1.ALL_BS_SUM < 0 AND T2.ALL_BS_SUM  <= T1.ALL_BS_SUM  THEN  'SELL -'

            ELSE NULL END AS BS_FLAG
            ,T1.CLOSE_ADJ_PRICE AS CLOSE_STIKER_PRICE
            ,T1.CLOSE_ADJ_PRICE-T2.CLOSE_ADJ_PRICE AS DIFF_PRICE
            ,(T1.CLOSE_ADJ_PRICE-T2.CLOSE_ADJ_PRICE )/T1.CLOSE_ADJ_PRICE AS DIFF_PRICE_PRC
        FROM PUBLIC.DF_BUY_SELL_FLAG_2  T1
        LEFT JOIN PUBLIC.DF_BUY_SELL_FLAG  T2 ON T1.TICKER =T2.TICKER AND T1.SEQ_EVENT+1 =T2.SEQ_EVENT 
    

  )  AS T2 
  WHERE  T1.TICKER=T2.TICKER;
  



--BS_FLAG_TRENT_DAYS_IN                                    
      
UPDATE DF_BUY_SELL_FLAG_2 T1
SET
 	BS_FLAG_TRENT_DAYS_IN	=	T2.	BS_FLAG_TRENT_DAYS_IN

FROM (

   SELECT 
    T1.TICKER
	,T1.PRICE_DATE 
    ,T1.ALL_BS_SUM
	,T2.PRICE_DATE AS BS_FLAG_SINCE_DATE
    ,T2.ALL_BS_SUM AS ALL_BS_SUM_START
	,T2.SEQ_EVENT- T1.SEQ_EVENT +1 AS BS_FLAG_TRENT_DAYS_IN  -- EXCLUDING  NO WORKING DAYS 
    FROM DF_BUY_SELL_FLAG_2  T1 
	LEFT JOIN PUBLIC.DF_BUY_SELL_FLAG  T2 ON   T1.TICKER=T2.TICKER 
    WHERE  1=1
    AND  T2.SEQ_EVENT+1 = ( SELECT  MIN (T2A.SEQ_EVENT)
                    FROM PUBLIC.DF_BUY_SELL_FLAG  T2A
                    WHERE CASE WHEN T1.ALL_BS_SUM > 0  THEN T2A.ALL_BS_SUM < 0 
                                    ELSE  T2A.ALL_BS_SUM > 0 END  -- FIND THE LATES OPOSITE , TO GET DAY AFTER 
                    AND T2A.TICKER = T2.TICKER
                    AND T2A.PRICE_DATE< T1.PRICE_DATE 
                   ) 
  
  )  AS T2 
  WHERE  T1.TICKER=T2.TICKER;

  

/*

-- ZACKS DATA 
*/

--LATEST 

UPDATE  DF_BUY_SELL_FLAG_2  T1
SET

Z_RANK = T2.Z_RANK
,Z_SECTOR_CLASS = T2.Z_SECTOR_CLASS
,Z_INDUSTRY_RANK = T2.Z_INDUSTRY_RANK
,Z_EXP_GROWTH = T2.Z_EXP_GROWTH
,Z_LOAD_DATE = T2.Z_LOAD_DATE
,Z_RANK_NUM=T2.Z_RANK_NUM
FROM (
    SELECT
     T1.PRICE_DATE
    ,T2.TICKER
    ,T2.RANK AS Z_RANK
    ,T2.Z_RANK_NUM AS Z_RANK_NUM
    ,T2.SECTOR_CLASS AS Z_SECTOR_CLASS
    ,T2.INDUSTRY_RANK AS Z_INDUSTRY_RANK
    ,T2.EXP_GROWTH AS Z_EXP_GROWTH
    ,T2.LOAD_DATE AS Z_LOAD_DATE
    FROM DF_BUY_SELL_FLAG_2   T1
    LEFT JOIN  DF_H_ZACKS_INDICATORS T2 ON T1.TICKER= T2.TICKER  
                                    AND T2.LOAD_DATE = ( SELECT  MAX ( T2A.LOAD_DATE )
                                                          FROM DF_H_ZACKS_INDICATORS T2A
                                                          WHERE T2.TICKER = T2A.TICKER
                                                          AND T2A.LOAD_DATE<= T1.PRICE_DATE ) 
    WHERE 1=1
    
    --AND T1.TICKER  = 'LOGI'

      )  AS T2 
WHERE  T1.TICKER=T2.TICKER
AND  T1.PRICE_DATE=T2.PRICE_DATE;


/*
LAST BEFORE 
*/



UPDATE  DF_BUY_SELL_FLAG_2  T1
SET

Z_RANK_LB = T2.Z_RANK
,Z_RANK_LB_NUM =T2.Z_RANK_NUM
,Z_LOAD_DATE_LB = T2.Z_LOAD_DATE

FROM (
    SELECT
     T1.PRICE_DATE
    ,T2.TICKER
    ,T2.RANK AS Z_RANK
    ,T2.Z_RANK_NUM AS Z_RANK_NUM
    ,T2.SECTOR_CLASS AS Z_SECTOR_CLASS
    ,T2.INDUSTRY_RANK AS Z_INDUSTRY_RANK
    ,T2.EXP_GROWTH AS Z_EXP_GROWTH
    ,T2.LOAD_DATE AS Z_LOAD_DATE
    FROM DF_BUY_SELL_FLAG_2   T1
    LEFT JOIN  DF_H_ZACKS_INDICATORS T2 ON T1.TICKER= T2.TICKER  
                                    AND T2.LOAD_DATE = ( SELECT  MAX ( T2A.LOAD_DATE )
                                                          FROM DF_H_ZACKS_INDICATORS T2A
                                                          WHERE T2.TICKER = T2A.TICKER
														 AND T2A.RANK <>T1.Z_RANK 
                                                          AND T2A.LOAD_DATE<= T1.Z_LOAD_DATE ) 

      )  AS T2 
WHERE  T1.TICKER=T2.TICKER
AND  T1.PRICE_DATE=T2.PRICE_DATE;


/*

-- YAHOO 
*/

--LATEST
UPDATE  DF_BUY_SELL_FLAG_2  T1
SET
Y_RANK = T2.Y_RANK
,Y_RANK_NUM = T2.Y_RANK_NUM
,Y_PRICE_1Y_EST = T2.Y_PRICE_1Y_EST
,Y_LOAD_DATE = T2.Y_LOAD_DATE
FROM (

SELECT 
        T1.PRICE_DATE
        ,T1.TICKER
        ,T2.Y_RANK
        , T2.Y_RANK_NUM AS Y_RANK_NUM 
        ,	CAST (T2.Y_PRICE_1Y_EST AS DECIMAL (10,2)) AS Y_PRICE_1Y_EST
        ,	T2.LOAD_DATE AS Y_LOAD_DATE

FROM DF_BUY_SELL_FLAG_2   T1
LEFT JOIN  DF_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER AND T2.LOAD_DATE = ( SELECT  MAX ( T2A.LOAD_DATE )
																			  FROM DF_YAHOO_RECOMMENDATIONS T2A
																			  WHERE T2.TICKER = T2A.TICKER
																			  AND T2A.LOAD_DATE<= T1.PRICE_DATE )  

    WHERE 1=1
    
  --AND T1.TICKER  = 'LOGI'
      )  AS T2 
WHERE  T1.TICKER=T2.TICKER
AND  T1.PRICE_DATE=T2.PRICE_DATE;

/*
--LAST BEFORE 
*/

UPDATE  DF_BUY_SELL_FLAG_2  T1
SET


Y_RANK_LB  = T2.Y_RANK
,Y_RANK_LB_NUM = T2.Y_RANK_NUM
,Y_LOAD_DATE_LB  = T2.Y_LOAD_DATE

FROM (

SELECT 
        T1.PRICE_DATE
        ,T1.TICKER
        ,T2.Y_RANK
        , T2.Y_RANK_NUM AS Y_RANK_NUM 
        ,	CAST (T2.Y_PRICE_1Y_EST AS DECIMAL (10,2)) AS Y_PRICE_1Y_EST
        ,	T2.LOAD_DATE AS Y_LOAD_DATE

FROM DF_BUY_SELL_FLAG_2   T1
LEFT JOIN  DF_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER AND T2.LOAD_DATE = ( SELECT  MAX ( T2A.LOAD_DATE )
																			  FROM DF_YAHOO_RECOMMENDATIONS T2A
																			  WHERE T2.TICKER = T2A.TICKER
                                                                              AND T2A.Y_RANK <>T1.Y_RANK 
																			  AND T2A.LOAD_DATE<= T1.Y_LOAD_DATE )  

    WHERE 1=1
    
  --AND T1.TICKER  = 'LOGI'
      )  AS T2 
WHERE  T1.TICKER=T2.TICKER
AND  T1.PRICE_DATE=T2.PRICE_DATE;




/*
COMBAINED 
*/
--REC_RANK_NUM
UPDATE  DF_BUY_SELL_FLAG_2  SET 
REC_RANK_NUM = ROUND (((COALESCE (Y_RANK_NUM, Z_RANK_NUM)
                                                    + 
                                                     COALESCE ( Z_RANK_NUM,Y_RANK_NUM)) 
                                                        / 2)
                                                        -.01)  
 , REC_RANK_LB_NUM = ROUND (((COALESCE (Y_RANK_LB_NUM, Z_RANK_LB_NUM)
                                                    + 
                                    COALESCE ( Z_RANK_LB_NUM,Y_RANK_LB_NUM)) 
                                                        / 2)
                                                        -.01)  ; 




--REC_RANK 
UPDATE  DF_BUY_SELL_FLAG_2  SET REC_RANK =  CASE WHEN REC_RANK_NUM =5 THEN '5-STRONG' 
                                            WHEN REC_RANK_NUM =4 THEN '4-SELL' 
                                            WHEN REC_RANK_NUM =3 THEN '3-HOLD' 
                                            WHEN REC_RANK_NUM =2 THEN '2-BUY' 
                                            WHEN REC_RANK_NUM =1 THEN '1-STRONG' 
                                            ELSE  NULL END;



-- ACTUAL VARIANCES 
UPDATE DF_BUY_SELL_FLAG_2  T1 SET REC_VAR_ACTUAL = (REC_RANK_NUM- REC_RANK_LB_NUM ) * -1 ;
UPDATE DF_BUY_SELL_FLAG_2  T1 SET REC_VAR_ACTUAL = 0 WHERE  REC_RANK_LB_NUM =0;

--Z_VAR_ACTUAL_DAYSDIFF
UPDATE DF_BUY_SELL_FLAG_2  T1 SET 
Z_VAR_ACTUAL_DAYSDIFF=   Z_LOAD_DATE - Z_LOAD_DATE_LB; 
--Y_VAR_ACTUAL_DAYSDIFF
UPDATE DF_BUY_SELL_FLAG_2  T1 SET 
Y_VAR_ACTUAL_DAYSDIFF=   Y_LOAD_DATE - Y_LOAD_DATE_LB ; 
--REC_VAR_ACTUAL_DAYSDIFF
UPDATE DF_BUY_SELL_FLAG_2  T1 SET
 REC_VAR_ACTUAL_DAYSDIFF =   ( COALESCE ( Z_VAR_ACTUAL_DAYSDIFF , Y_VAR_ACTUAL_DAYSDIFF) 
                                +
                                 COALESCE ( Y_VAR_ACTUAL_DAYSDIFF ,Z_VAR_ACTUAL_DAYSDIFF)  
                              )/ 2 ;                                 


--REC_RANK_IND
UPDATE DF_BUY_SELL_FLAG_2  T1 SET REC_RANK_IND = 'Z' WHERE  Z_RANK IS NOT NULL; 
UPDATE DF_BUY_SELL_FLAG_2  T1 SET REC_RANK_IND = COALESCE (REC_RANK_IND, '' )||'Y' WHERE  Y_RANK IS NOT NULL;

	