CREATE OR REPLACE PROCEDURE etl06_df_buy_sell_flag()
LANGUAGE plpgsql
AS $procedure$
BEGIN



-- Drotp table Only 
DROP TABLE IF EXISTS df_buy_sell_flag;

create table df_buy_sell_flag  as 
SELECT 
	CAST (	TICKER	AS 	VARCHAR (15)	) AS 	TICKER
,	CAST (	DATE	AS 	DATE 	) AS 	DATE
,	CAST (	OPEN	AS 	DECIMAL (18, 6)	) AS 	OPEN
,	CAST (	HIGH	AS 	DECIMAL (18, 6)	) AS 	HIGH
,	CAST (	LOW	AS 	DECIMAL (18, 6)	) AS 	LOW
,	CAST (	CLOSE	AS 	DECIMAL (18, 6)	) AS 	CLOSE
,	CAST (	ADJCLOSE	AS 	DECIMAL (18, 6)	) AS 	ADJCLOSE
,	CAST (	VOLUME	AS 	DECIMAL (18, 6)	) AS 	VOLUME

,	CAST (	MA_10	AS 	DECIMAL (18, 6)	) AS 	MA_10
,	CAST (	MA_10_TREND	AS 	VARCHAR (20)	) AS 	MA_10_TREND
,	CAST (	MA_10_TREND_CHANGE	AS 	VARCHAR (10)	) AS 	MA_10_TREND_CHANGE
,	CAST (	MA_10_BS_FLAG	AS 	INT	) AS 	MA_10_BS_FLAG
,	CAST (	EMA8	AS 	DECIMAL (18, 6)	) AS 	EMA8
,	CAST (	EMA18	AS 	DECIMAL (18, 6)	) AS 	EMA18
,	CAST (	MACD	AS 	DECIMAL (18, 6)	) AS 	MACD
,	CAST (	SIGNAL9	AS 	DECIMAL (18, 6)	) AS 	SIGNAL9
,	CAST (	MACD_SIGNAL9_DIFF	AS 	DECIMAL (18, 6)	) AS 	MACD_SIGNAL9_DIFF
,	CAST (	MACD_TREND	AS 	VARCHAR (20)	) AS 	MACD_TREND
,	CAST (	MACD_TREND_CHANGE	AS 	VARCHAR (10)	) AS 	MACD_TREND_CHANGE
,	CAST (	MACD_BS_FLAG	AS 	INT	) AS 	MACD_BS_FLAG
,	CAST (	MIN14	AS 	DECIMAL (18, 6)	) AS 	MIN14
,	CAST (	MAX14	AS 	DECIMAL (18, 6)	) AS 	MAX14
,	CAST (	AVG_MIN_MAX	AS 	DECIMAL (18, 6)	) AS 	AVG_MIN_MAX
,	CAST (	AVG_MIN_MAX_VS_CLOSE	AS 	DECIMAL (18, 6)	) AS 	AVG_MIN_MAX_VS_CLOSE
,	CAST (	AVG_MIN_MAX_VS_CLOSE_EMA5	AS 	DECIMAL (18, 6)	) AS 	AVG_MIN_MAX_VS_CLOSE_EMA5
,	CAST (	AVG_MIN_MAX_VS_CLOSE_EMA5_2	AS 	DECIMAL (18, 6)	) AS 	AVG_MIN_MAX_VS_CLOSE_EMA5_2
,	CAST (	DIFF_MIN_MAX	AS 	DECIMAL (18, 6)	) AS 	DIFF_MIN_MAX
,	CAST (	DIFF_MIN_MAX_EMA5	AS 	DECIMAL (18, 6)	) AS 	DIFF_MIN_MAX_EMA5
,	CAST (	DIFF_MIN_MAX_EMA5_2	AS 	DECIMAL (18, 6)	) AS 	DIFF_MIN_MAX_EMA5_2
,	CAST (	SMI	AS 	DECIMAL (18, 6)	) AS 	SMI
,	CAST (	SIGNAL_LINE	AS 	DECIMAL (18, 6)	) AS 	SIGNAL_LINE
,	CAST (	SMI_SIGNAL_LINE_DIFF	AS 	DECIMAL (18, 6)	) AS 	SMI_SIGNAL_LINE_DIFF
,	CAST (	SMI_TREND	AS 	VARCHAR (20)	) AS 	SMI_TREND
,	CAST (	SMI_TREND_CHANGE	AS 	VARCHAR (10)	) AS 	SMI_TREND_CHANGE
,	CAST (	SMI_BS_FLAG	AS 	INT	) AS 	SMI_BS_FLAG
,	CAST (	ALL_BS_SUM	AS 	INT	) AS 	ALL_BS_SUM
,	CAST (	ALL_BS_FLAG	AS 	VARCHAR (10)	) AS 	ALL_BS_FLAG
,	CAST (	ALL_BS_FLAG_SEEN_PRICES	AS 	VARCHAR (10)	) AS 	ALL_BS_FLAG_SEEN_PRICES
,	CAST (	ALL_BS_FLAG_1MINUS	AS 	VARCHAR (10)	) AS 	ALL_BS_FLAG_1MINUS
,	CAST (	ALL_BS_FLAG_SEEN_PRICES_1MINUS	AS 	DECIMAL (18, 6)	) AS 	ALL_BS_FLAG_SEEN_PRICES_1MINUS
,	CAST (	ALL_BS_FLAG_SEEN_PRICES_1MINUS_ACTUAL	AS 	DECIMAL (18, 6)	) AS 	ALL_BS_FLAG_SEEN_PRICES_1MINUS_ACTUAL
, ROW_NUMBER() OVER(   PARTITION BY T1.TICKER   ORDER BY DATE DESC ) AS SEQ_EVENT
, CURRENT_DATE AS LOAD_DATE
FROM DF_BUY_SELL_FLAGS t1
--where ticker = 'LOGI'
;


-- Index created

CREATE  INDEX df_buy_sell_flag_IX_1 ON df_buy_sell_flag  (Date);  
CREATE  INDEX df_buy_sell_flag_IX_2 ON df_buy_sell_flag  (TICKER);  
CREATE  INDEX df_buy_sell_flag_IX_3 ON df_buy_sell_flag  (TICKER , Date desc  );  
CREATE  INDEX df_buy_sell_flag_IX_4 ON df_buy_sell_flag  (TICKER , Date asc  );  
CREATE  INDEX df_buy_sell_flag_IX_5  ON df_buy_sell_flag  (SEQ_EVENT  );  -- CREATE  INDEX df_buy_sell_flag_IX_1 ON df_buy_sell_flag  (Date);  

END
$procedure$


