

DELETE FROM FUNDAMENTALS_HISTORIC    AS T1
WHERE (T1.FUNDAMENTAL_ID , T1.TICKER, T1.YEAR) IN 
(SELECT T2.FUNDAMENTAL_ID 
 		, T2.TICKER
 		, T2.YEAR 
FROM  FUNDAMENTALS_HISTORIC_TEST AS T2
)

INSERT INTO FUNDAMENTALS_HISTORIC SELECT * FROM FUNDAMENTALS_HISTORIC_TEST

CREATE TABLE FUNDAMENTALS_HISTORIC_S AS SELECT * FROM FUNDAMENTALS_HISTORIC where 1=2


select * 
from FUNDAMENTALS_HISTORIC_S