
CREATE OR REPLACE PROCEDURE etl02_fundamental_H_update ()
LANGUAGE SQL
as $$


/*
************************************
 --1.-  CREATE A FORMATING TABLE FiRst 
 --2.- then Insert  NEW DATA TO FUNDAMENTALS_HISTORIC 
 - 3.- WICH WILL BE FUNDAMENTALS_HISTORIC
************************************ 
 */
 
--DF_FUNDAMENTALS_H_UPDATE
-- DROP TABLE IF EXISTS DF_FUNDAMENTALS_H_UPDATE;
-- CREATE TABLE DF_FUNDAMENTALS_H_UPDATE

-- (
	-- TICKER	VARCHAR(15)
-- ,	REPORT_PERIOD	INT
-- ,	TOTALREVENUE	DECIMAL (12,2) DEFAULT 0
-- ,	OPERATINGINCOME	DECIMAL (12,2) DEFAULT 0
-- ,	INCOMEBEFORETAX	DECIMAL (12,2) DEFAULT 0
-- ,	INCOMETAXEXPENSE	DECIMAL (12,2) DEFAULT 0
-- ,	EARNINGS	DECIMAL (12,2) DEFAULT 0
-- ,	FREECASHFLOW	DECIMAL (12,2) DEFAULT 0
-- ,	CASHANDCASHEQUIVALENTS	DECIMAL (12,2) DEFAULT 0
-- ,	TOTALLIAB	DECIMAL (12,2) DEFAULT 0
-- ,	TOTALSTOCKHOLDEREQUITY	DECIMAL (12,2) DEFAULT 0
-- ,	INVESTEDCAPITAL	DECIMAL (12,2) DEFAULT 0
-- ,	TAXRATE	DECIMAL (16,4) DEFAULT 0
-- ,	NOTPAD	DECIMAL (16,4) DEFAULT 0
-- ,	ROIC	DECIMAL (16,4) DEFAULT 0 
--
--,	LONGTERMDEBT DECIMAL (12,2) DEFAULT 0
--,	TOTALCURRENTASSETS DECIMAL (12,2) DEFAULT 0
--,	TOTALCURRENTLIABILITIES DECIMAL (12,2) DEFAULT 0


-- , LOAD_DATE DATE
-- );


DELETE FROM DF_FUNDAMENTALS_H_UPDATE;

-- INSERT  1  DF_INCOME_STATEMENT
INSERT INTO DF_FUNDAMENTALS_H_UPDATE 
SELECT 
	TICKER
,	REPORT_PERIOD
,	TOTALREVENUE
,	OPERATINGINCOME
,	INCOMEBEFORETAX
,	INCOMETAXEXPENSE

FROM PUBLIC.DF_INCOME_STATEMENT;


--DF_EARNINGS_Y_REVENUE
UPDATE DF_FUNDAMENTALS_H_UPDATE  AS T1 
SET EARNINGS=T2.EARNINGS
FROM  (
SELECT 
	TICKER
,	REPORT_PERIOD
,EARNINGS AS EARNINGS
FROM PUBLIC.DF_EARNINGS_Y_REVENUE
) AS T2
WHERE ( T1.TICKER=T2.TICKER AND  T1.REPORT_PERIOD = T2.REPORT_PERIOD );


--DF_CASH_FLOW_STATEMENT
UPDATE DF_FUNDAMENTALS_H_UPDATE  AS T1 
SET FREECASHFLOW=T2.FREECASHFLOW
FROM  (
SELECT 
	TICKER
,	REPORT_PERIOD
,TOTALCASHFROMOPERATINGACTIVITIES + CAPITALEXPENDITURES AS FREECASHFLOW --CAPITALEXPENDITURES is in negative from source 
FROM PUBLIC.DF_CASH_FLOW_STATEMENT
) AS T2
WHERE ( T1.TICKER=T2.TICKER AND  T1.REPORT_PERIOD = T2.REPORT_PERIOD );



--DF_BALANCE
UPDATE DF_FUNDAMENTALS_H_UPDATE  AS T1 
SET 
CASHANDCASHEQUIVALENTS=T2.CASHANDCASHEQUIVALENTS
,INVESTEDCAPITAL=T2.INVESTEDCAPITAL
,TOTALLIAB=T2.TOTALLIAB
,TOTALSTOCKHOLDEREQUITY=T2.TOTALSTOCKHOLDEREQUITY

,	LONGTERMDEBT	=T2.	LONGTERMDEBT
,	TOTALCURRENTASSETS	=T2.	TOTALCURRENTASSETS
,	TOTALCURRENTLIABILITIES	=T2.	TOTALCURRENTLIABILITIES


FROM  (
SELECT 
	TICKER
,	REPORT_PERIOD
,CASH+ SHORTTERMINVESTMENTS AS CASHANDCASHEQUIVALENTS
,TOTALSTOCKHOLDEREQUITY + TOTALLIAB +  CASH+ SHORTTERMINVESTMENTS AS  INVESTEDCAPITAL
,TOTALLIAB AS TOTALLIAB
,TOTALSTOCKHOLDEREQUITY AS  TOTALSTOCKHOLDEREQUITY

,	LONGTERMDEBT	AS	LONGTERMDEBT
,	TOTALCURRENTASSETS	AS	TOTALCURRENTASSETS
,	TOTALCURRENTLIABILITIES	AS	TOTALCURRENTLIABILITIES



FROM PUBLIC.DF_BALANCE
) AS T2
WHERE ( T1.TICKER=T2.TICKER AND  T1.REPORT_PERIOD = T2.REPORT_PERIOD );


--DF_INCOME_STATEMENT
UPDATE DF_FUNDAMENTALS_H_UPDATE  AS T1 
SET 
TAXRATE=T2.TAXRATE
,NOTPAD=T2.NOTPAD
FROM  (
SELECT 
TICKER
,REPORT_PERIOD
,CAST (INCOMETAXEXPENSE / nullif (INCOMEBEFORETAX, 0) AS DECIMAL (12,6)) AS TAXRATE
,OPERATINGINCOME * (1 - CAST (INCOMETAXEXPENSE / nullif ( INCOMEBEFORETAX, 0 ) AS DECIMAL (12,6))  ) AS NOTPAD
FROM PUBLIC.DF_INCOME_STATEMENT
) AS T2
WHERE ( T1.TICKER=T2.TICKER AND  T1.REPORT_PERIOD = T2.REPORT_PERIOD );

--ROIC -  Operatin income  after tax  /  Book Value Investment Capital 
--What is ROIC and  comparision with other similar ratios 
-- https://learn.robinhood.com/articles/3jB0ufT6VhxpsJthBMuY1o/what-is-return-on-invested-capital-roic/

UPDATE DF_FUNDAMENTALS_H_UPDATE  AS T1  SET 
ROIC =NOTPAD/ NULLIF(INVESTEDCAPITAL,0)    --NOPAD Net operating profit after tax 
,LOAD_DATE = CURRENT_DATE;


/* ************************************************
--GET LATEST 2 YEARS Fot those already in the FUNDAMENTALS_HISTORIC
***************************************************
*/
DELETE FROM  DF_FUNDAMENTALS_H_UPDATE  t1
WHERE REPORT_PERIOD NOT IN (
                        SELECT DISTINCT TA1.REPORT_PERIOD  
                        FROM DF_FUNDAMENTALS_H_UPDATE as TA1
                        ORDER BY TA1.REPORT_PERIOD DESC
                        LIMIT 2)
and T1.TICKER in (

SELECT T2.TICKER
FROM PUBLIC.FUNDAMENTALS_HISTORIC as T2
);

/* ************************************************
----INSERT NEW DATA 

***************************************************
*/

DELETE FROM PUBLIC.FUNDAMENTALS_HISTORIC WHERE (TICKER,YEAR) IN(	SELECT TICKER, REPORT_PERIOD	FROM DF_FUNDAMENTALS_H_UPDATE);

-- TOTALREVENUE
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.	FUNDAMENTAL_ID
,T1.TICKER
,T1.TOTALREVENUE  --CHANGE THIS TOO 
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) =  'TOTALREVENUE';--CHANGE THIS TOO 


-- OPERATINGINCOME
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.OPERATINGINCOME
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'OPERATINGINCOME';--CHANGE THIS TOO


-- INCOMEBEFORETAX
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.INCOMEBEFORETAX
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'INCOMEBEFORETAX';--CHANGE THIS TOO

-- INCOMETAXEXPENSE
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.INCOMETAXEXPENSE
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'INCOMETAXEXPENSE';--CHANGE THIS TOO


-- EARNINGS
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.EARNINGS
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'EARNINGS';--CHANGE THIS TOO


-- FREECASHFLOW
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.FREECASHFLOW
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'FREECASHFLOW';--CHANGE THIS TOO


-- CASHANDCASHEQUIVALENTS
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.CASHANDCASHEQUIVALENTS
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'CASHANDCASHEQUIVALENTS';--CHANGE THIS TOO


-- TOTALLIAB
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.TOTALLIAB
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'TOTALLIAB';--CHANGE THIS TOO


-- TOTALSTOCKHOLDEREQUITY
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.TOTALSTOCKHOLDEREQUITY
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'TOTALSTOCKHOLDEREQUITY';--CHANGE THIS TOO


-- INVESTEDCAPITAL
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.INVESTEDCAPITAL
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'INVESTEDCAPITAL';--CHANGE THIS TOO


-- TAXRATE
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.TAXRATE
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'TAXRATE';--CHANGE THIS TOO


-- NOTPAD
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.NOTPAD
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'NOTPAD';--CHANGE THIS TOO


-- ROIC
INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.ROIC
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  public.df_fundamental_id AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'ROIC';--CHANGE THIS TOO


-- LONGTERMDEBT

INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.LONGTERMDEBT
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  PUBLIC.DF_FUNDAMENTAL_ID AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'LONGTERMDEBT';--CHANGE THIS TOO



-- TOTALCURRENTASSETS

INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.TOTALCURRENTASSETS
,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  PUBLIC.DF_FUNDAMENTAL_ID AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'TOTALCURRENTASSETS';--CHANGE THIS TOO




-- TOTALCURRENTLIABILITIES


INSERT INTO  PUBLIC.FUNDAMENTALS_HISTORIC 
SELECT 
T2.FUNDAMENTAL_ID
,T1.TICKER
,T1.TOTALCURRENTLIABILITIES

,REPORT_PERIOD AS YEAR
,T1.LOAD_DATE
FROM DF_FUNDAMENTALS_H_UPDATE  AS T1
LEFT JOIN  PUBLIC.DF_FUNDAMENTAL_ID AS T2 ON UPPER( FUNDAMENTAL_NAME) = 'TOTALCURRENTLIABILITIES';--CHANGE THIS TOO





-- FOLLOW SNIP DELETE ANY YEAR WITH NOT DATA AT ALL 

DELETE FROM PUBLIC.FUNDAMENTALS_HISTORIC 
WHERE (TICKER, YEAR ) IN (
                        SELECT TICKER, YEAR  
                        FROM PUBLIC.FUNDAMENTALS_HISTORIC 
                        GROUP BY  TICKER, YEAR 
                        HAVING SUM(VALUE) =0) ; 

DELETE FROM FUNDAMENTALS_HISTORIC 
WHERE 	TICKER IN (				
        SELECT  DISTINCT TICKER
        FROM (
        SELECT 
        FUNDAMENTAL_ID 
        ,TICKER
        ,YEAR
        ,COUNT (*) COUNTDD 
        FROM  PUBLIC.fundamentals_historic T1
        WHERE 1=1
        --1.TICKER =  'ULVR.L'
        GROUP BY 
        FUNDAMENTAL_ID 
        ,TICKER
        ,YEAR
        HAVING COUNT(*) >1
        ) R);
                            
                            
                            
-- Index created 
DROP INDEX IF EXISTS FUNDAMENTALS_HISTORIC_IX_1;
DROP INDEX IF EXISTS FUNDAMENTALS_HISTORIC_IX_2;
DROP INDEX IF EXISTS FUNDAMENTALS_HISTORIC_IX_3;
DROP INDEX IF EXISTS FUNDAMENTALS_HISTORIC_IX_4;
DROP INDEX IF EXISTS FUNDAMENTALS_HISTORIC_IX_5;




CREATE  INDEX FUNDAMENTALS_HISTORIC_IX_1 ON FUNDAMENTALS_HISTORIC  (TICKER);  
CREATE  INDEX FUNDAMENTALS_HISTORIC_IX_2 ON FUNDAMENTALS_HISTORIC  (TICKER , FUNDAMENTAL_ID    );  
CREATE  INDEX FUNDAMENTALS_HISTORIC_IX_3 ON FUNDAMENTALS_HISTORIC  (year desc );  
CREATE  INDEX FUNDAMENTALS_HISTORIC_IX_4 ON FUNDAMENTALS_HISTORIC  (year asc ); 
CREATE  INDEX FUNDAMENTALS_HISTORIC_IX_5 ON FUNDAMENTALS_HISTORIC  (FUNDAMENTAL_ID); 
$$;

