CREATE OR REPLACE PROCEDURE etl07_Recomendations_h_update ()
LANGUAGE SQL
as $$


/* UPDATED ZACKS HISTORY  */
--DELETE IF DATA EXISTS 
DELETE FROM DF_H_ZACKS_INDICATORS T1
WHERE   (T1.TICKER , LOAD_DATE  )  IN (  SELECT T1A.TICKER , CAST (LOAD_DATE AS DATE ) as  LOAD_DATE  FROM DF_ZACKS_INDICATORS T1A);
--INSERT
INSERT INTO DF_H_ZACKS_INDICATORS 
 ( TICKER 
   ,Z_RANK 
   ,Z_RANK_NUM 
   ,Z_SECTOR_CLASS 
   ,Z_INDUSTRY_RANK  
   ,Z_EXP_GROWTH 
   ,PERIOD  
   ,LOAD_DATE )
   
SELECT 
	TICKER
,	Z_RANK
,( CAST ( SUBSTRING(T1.Z_RANK FROM '[0-9]+') AS INT )) as Z_RANK_NUM
,	Z_SECTOR_CLASS
,	Z_INDUSTRY_RANK
,	CAST (Z_EXP_GROWTH AS DECIMAL (10,2)) AS Z_EXP_GROWTH
,	PERIOD
,	CAST (LOAD_DATE AS DATE ) AS LOAD_DATE
FROM DF_ZACKS_INDICATORS T1;


--UPDATE  DF_H_ZACKS_INDICATORS  SET  Z_RANK_NUM   = ( CAST ( SUBSTRING(RANK FROM '[0-9]+') AS INT )) ;

/* ********************************
--- Yahoo Recomendations HISTORY
********************************* */
DELETE FROM DF_H_YAHOO_RECOMMENDATIONS T1
WHERE   (T1.TICKER , LOAD_DATE  )  IN ( 
                     SELECT 
                     T1A.TICKER 
                     ,CAST (LOAD_DATE AS DATE ) as  LOAD_DATE  
                     FROM DF_YAHOO_RECOMMENDATIONS_IMP T1A);



--INSERT
INSERT INTO DF_H_YAHOO_RECOMMENDATIONS 
 ( 
 	ticker
,	y_rank
,	y_rank_num
,	y_rank_analyst_num
,	profit_margins
,	y_price_1y_est
,	y_revenue_growth_est
,	y_earnings_growth_est
,	growth_est_next_year
,	growth_est_next_5_years
,	market_cap
,	avg_volume
,	eps
,	pe_ratio
,	ss_shares_outstanding
,	dividend_rate_per_share
,	dividend_yield
,	load_date

 )
SELECT 
    TICKER
    ,	 CASE WHEN UPPER(RECOMMENDATIONKEY) = 'UNDERPERFORM' THEN '4-SELL' 
                WHEN UPPER(RECOMMENDATIONKEY) = 'HOLD' THEN '3-HOLD' 
                WHEN UPPER(RECOMMENDATIONKEY) = 'BUY' THEN '2-BUY' 
                WHEN UPPER(RECOMMENDATIONKEY) = 'STRONG_BUY' THEN '1-STRONG' 
                        ELSE  NULL END  AS Y_RANK
    , ROUND(CAST  (Y_RANK AS  NUMERIC )-.01) AS Y_RANK_NUM 

    ,cast (y_rank_analyst_num  as int ) as  y_rank_analyst_num  		
    ,CAST  (PROFIT_MARGINS AS NUMERIC ) as PROFIT_MARGINS
    ,CAST (Y_PRICE_1Y_EST AS DECIMAL (14,2)) AS Y_PRICE_1Y_EST
	    ,cast (y_revenue_growth_est	AS decimal(14,6) ) AS	y_revenue_growth_est
    ,cast (y_earnings_growth_est	AS decimal(14,6) ) AS	y_earnings_growth_est
    ,cast ( replace(  replace( growth_est_next_year, '%', '') , ',' , '') as decimal(14,4))/100 as growth_est_next_year
    ,cast ( replace(  replace( growth_est_next_5_years, '%', '') , ',' , '') as decimal(14,4))/100 as  growth_est_next_5_years
    ,cast (market_cap as float) as market_cap
    ,cast (avg_volume as float ) as avg_volume
    ,cast (eps	AS decimal(14,6) ) AS	eps
    ,cast (pe_ratio	AS decimal(14,6) ) AS	pe_ratio
    ,cast (ss_shares_outstanding	as float)as	ss_shares_outstanding
    ,cast (dividend_rate_per_share	as float) as	dividend_rate_per_share
    ,cast (dividend_yield	as float) as	dividend_yield
    ,CAST (LOAD_DATE AS DATE )  AS LOAD_DATE
FROM DF_YAHOO_RECOMMENDATIONS_IMP;


--  fixes on  DF_YAHOO_RECOMMENDATIONS_IMP




-- QUERRY TO UPDATED NAMES 



UPDATE DF_H_TICKER_NAME T1
SET
NAME	=	T2.	NAME
,MARKET_CAP	=	T2.	MARKET_CAP
,COUNTRY	=	T2.	COUNTRY
,VOLUME	=	T2.	VOLUME
,SECTOR	=	T2.	SECTOR
,INDUSTRY	=	T2.	INDUSTRY
,MARKET	=	T2.	MARKET
FROM (
    SELECT 
	TICKER
,	NAME
,	MARKET_CAP
,	COUNTRY
, null as ipo_year
,	avg_volume as VOLUME
,	SECTOR
,	INDUSTRY
,	MARKET
FROM DF_YAHOO_RECOMMENDATIONS_IMP
                                                      
      )  AS T2 
WHERE  T1.TICKER=T2.TICKER ;



-- NEW INSERTS

INSERT INTO DF_H_TICKER_NAME 
SELECT 
	TICKER
,	NAME
,	MARKET_CAP
,	COUNTRY
 , NULL AS IPO_YEAR

,	AVG_VOLUME AS VOLUME
,	SECTOR
,	INDUSTRY
,	MARKET
FROM DF_YAHOO_RECOMMENDATIONS_IMP
WHERE TICKER NOT IN ( SELECT  TICKER 	FROM DF_H_TICKER_NAME);





/*
TEMP MERGE  UPDATED  OLD DATA WITH NEW DATA  
*/


--Y_RANK
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
Y_RANK = T2.	Y_RANK
, Y_RANK_NUM =T2.	Y_RANK_NUM 
, Y_RANK_ANALYST_NUM = T2.	Y_RANK_ANALYST_NUM 
, PROFIT_MARGINS = T2.	PROFIT_MARGINS 


FROM (

  SELECT DISTINCT 
   T1. TICKER
	,T2.Y_RANK
	,T2.Y_RANK_NUM
	,T2.Y_RANK_ANALYST_NUM
	,T2.PROFIT_MARGINS
    ,T1.LOAD_DATE
    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
	LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
    WHERE    T1.Y_RANK IS  NULL  -- HERE CHANGE 
	AND  T2.Y_RANK IS NOT NULL  -- HERE CHANGE 
    AND T2.LOAD_DATE = (
                        SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
                        FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A  
                        WHERE  T2A.Y_RANK IS NOT NULL  -- HERE CHANGE 
						AND T2A.TICKER=T2.TICKER
                        AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
                        )
					
                        
	
      )  AS T2 
WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ; 

--Y_PRICE_1Y_EST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
Y_PRICE_1Y_EST	=	T2.	Y_PRICE_1Y_EST



FROM (
        SELECT 
        T1.TICKER
        ,T2.	Y_PRICE_1Y_EST
        ,T1.LOAD_DATE
          FROM  DF_H_YAHOO_RECOMMENDATIONS T1
        LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
        WHERE 1=1
        AND  T1.Y_PRICE_1Y_EST IS  NULL  -- HERE CHANGE 
        AND  T2.Y_PRICE_1Y_EST IS  NOT  NULL  -- HERE CHANGE 
        AND T2.LOAD_DATE = (SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
                                 FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
                                WHERE  T2A.Y_PRICE_1Y_EST IS NOT NULL 
                              AND T2A.TICKER=T2.TICKER
                                AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
                                )
	
      )  AS T2 

WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ; 


--UPDATES FROM  Y_REVENUE_GROWTH_EST   &  Y_EARNINGS_GROWTH_EST  1ST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
Y_REVENUE_GROWTH_EST	=	T2.	Y_REVENUE_GROWTH_EST
,Y_EARNINGS_GROWTH_EST	=	T2.	Y_EARNINGS_GROWTH_EST
FROM (
        SELECT 
        T1.TICKER
        ,T2.Y_REVENUE_GROWTH_EST
        ,T2.Y_EARNINGS_GROWTH_EST
        ,T1.LOAD_DATE
        FROM  DF_H_YAHOO_RECOMMENDATIONS T1
        LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
        WHERE 1=1 
        AND      T1.Y_REVENUE_GROWTH_EST IS  NULL   -- HERE TO CHANGE 
        AND T2.Y_REVENUE_GROWTH_EST IS NOT  NULL   -- HERE TO CHANGE 
        AND T2.LOAD_DATE = (SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
                                 FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
                                WHERE  T2A.Y_REVENUE_GROWTH_EST  IS NOT NULL  
                              AND T2A.TICKER=T2.TICKER
                                AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
                                )
	
      )  AS T2 
WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;



--UPDATES FROM  GROWTH_EST_NEXT_YEAR  & GROWTH_EST_NEXT_5_YEARS 1ST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
GROWTH_EST_NEXT_YEAR	=	T2.	GROWTH_EST_NEXT_YEAR
,GROWTH_EST_NEXT_5_YEARS	=	T2.	GROWTH_EST_NEXT_5_YEARS

FROM (
		SELECT 
		T1.TICKER
		,T2.GROWTH_EST_NEXT_YEAR
		,T2.GROWTH_EST_NEXT_5_YEARS
       , T1.LOAD_DATE
	    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
	LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
		WHERE 1=1
AND  T1.GROWTH_EST_NEXT_5_YEARS IS  NULL  
 AND  T2 .GROWTH_EST_NEXT_5_YEARS IS NOT  NULL       

AND     T2.LOAD_DATE = (SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
								FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
								WHERE  T2A.GROWTH_EST_NEXT_5_YEARS  IS NOT NULL   -- HERE TO CHANGE 
								AND T2A.TICKER=T2.TICKER
								AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
								)

      )  AS T2 
WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;


--UPDATES FROM  MARKET_CAP  1ST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
MARKET_CAP	=	T2.	MARKET_CAP



FROM (
		SELECT 
		T1.TICKER
		,T2.MARKET_CAP
        ,T1.LOAD_DATE
	    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
	LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
		WHERE 1=1
          AND T1.MARKET_CAP IS  NULL 
                AND T2.MARKET_CAP IS  NOT NULL 
        AND T2.LOAD_DATE = (SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
								FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
												WHERE  T2A.MARKET_CAP  IS NOT NULL   -- HERE TO CHANGE 
								AND T2A.TICKER=T2.TICKER
								AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
								)

      )  AS T2 WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;




--UPDATES FROM  AVG_VOLUME  1ST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
AVG_VOLUME	=	T2.	AVG_VOLUME

FROM (
		SELECT 
		T1.TICKER
		,T2.AVG_VOLUME
        ,T1.LOAD_DATE
	    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
		WHERE 1=1
          AND T1.AVG_VOLUME IS  NULL 
                AND T2.AVG_VOLUME IS  NOT NULL 
        AND T2.LOAD_DATE = (SELECT MAX (T2A.LOAD_DATE )  -- EARLIES AFTER 
								FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
												WHERE  T2A.AVG_VOLUME   IS NOT NULL   -- HERE TO CHANGE 
								AND T2A.TICKER=T2.TICKER
								AND  T2A.LOAD_DATE <= T1.LOAD_DATE -- EARLIES AFTER 
								)

      )  AS T2 WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;
      
    
      
      
      

--UPDATES FROM  EPS &  PE_RATIO 
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
EPS	=	T2.	EPS
,PE_RATIO	=	T2.	PE_RATIO
FROM (
		SELECT 
		T1.TICKER
		,T2.EPS
        ,T2.PE_RATIO

        ,T1.LOAD_DATE
	    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
		WHERE 1=1
          AND T1.EPS IS  NULL 
                AND T2.EPS IS  NOT NULL 
        AND T2.LOAD_DATE = (SELECT MAX (T2A.LOAD_DATE ) -- MAX BEFORE 
								FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
												WHERE  T2A.EPS   IS NOT NULL   -- HERE TO CHANGE 
								AND T2A.TICKER=T2.TICKER
								AND  T2A.LOAD_DATE <= T1.LOAD_DATE -- MAX BEFORE 
								)

      )  AS T2 WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;
  

--UPDATES FROM  SS_SHARES_OUTSTANDING  1ST
UPDATE DF_H_YAHOO_RECOMMENDATIONS  T1
SET
SS_SHARES_OUTSTANDING	=	T2.	SS_SHARES_OUTSTANDING

FROM (
		SELECT 
		T1.TICKER
		,T2.SS_SHARES_OUTSTANDING
        ,T1.LOAD_DATE
	    FROM  DF_H_YAHOO_RECOMMENDATIONS T1
LEFT JOIN  DF_H_YAHOO_RECOMMENDATIONS T2 ON T1.TICKER= T2.TICKER
		WHERE 1=1
          AND T1.SS_SHARES_OUTSTANDING IS  NULL 
                AND T2.SS_SHARES_OUTSTANDING IS  NOT NULL 
        AND T2.LOAD_DATE = (SELECT MIN (T2A.LOAD_DATE )  -- EARLIES AFTER 
								FROM DF_H_YAHOO_RECOMMENDATIONS  AS  T2A
												WHERE  T2A.SS_SHARES_OUTSTANDING   IS NOT NULL   -- HERE TO CHANGE 
								AND T2A.TICKER=T2.TICKER
								AND  T2A.LOAD_DATE >= T1.LOAD_DATE -- EARLIES AFTER 
								)

      )  AS T2 WHERE  T1.TICKER=T2.TICKER AND T1.LOAD_DATE= T2.LOAD_DATE   ;

 $$;