CREATE OR REPLACE PROCEDURE  p04_porfolios_update ( )
LANGUAGE plpgsql
AS $procedure$
BEGIN


-- CANTOR PORFOLIO 
DROP TABLE IF EXISTS DF_CANTOR;
create TABLE DF_CANTOR as 
SELECT 
		TYPE
,		TICKER
,		SHARES
,		PRICE
,	CAST (	TRANS_DATE AS DATE ) AS TRANS_DATE
,		USD_COMMISION
,		ACTIVE_FLAG
, CURRENT_DATE AS LOAD_DATE
FROM DF_CANTOR_IMP;


-- ETORO
DROP TABLE IF EXISTS DF_ETORO;
CREATE TABLE DF_ETORO AS 
 
SELECT DISTINCT 
    TICKER
    ,PORFOLIO
    ,CAST (TRANS_DATE AS DATE ) AS TRANS_DATE
    FROM DF_ETORO_IMP
WHERE TICKER is  NOT NULL;

-- ALL
DROP TABLE IF EXISTS DF_PORFOLIO;
CREATE TABLE DF_PORFOLIO AS 

    SELECT 
        TICKER
        ,PORFOLIO
        ,TRANS_DATE
        FROM DF_ETORO
        
        UNION ALL
        
        SELECT 
        TICKER
        ,'CANTOR' AS PORFOLIO
        , TRANS_DATE
        FROM DF_CANTOR
        WHERE ACTIVE_FLAG = 1;
        
 
 ---DF_CANTOR
 
DROP TABLE IF EXISTS DF_CANTOR_VIEW;
CREATE TABLE DF_CANTOR_VIEW AS  
SELECT 
    T1.TRANS_DATE ,
    T1.TICKER,
    T1.SHARES,

    T1.PRICE AS TRANS_PRICE,
    T2.STIKER_PRICE AS ACTUAL_PRICE ,
    T2. Y_PRICE_1Y_EST  ,


    ((T2.STIKER_PRICE::DOUBLE PRECISION - T1.PRICE) * T1.SHARES::DOUBLE PRECISION / ( (T1.PRICE) * T1.SHARES::DOUBLE PRECISION)::DOUBLE PRECISION)::NUMERIC(10,6) AS PROFIT_PERC,
    T2.BS_FLAG,
    T2.bs_flag_trend_days_in,
    T2.NAME,
    T2.REC_RANK,
    T2.SCORE_VALUATION,
    (T1.PRICE) * T1.SHARES::DOUBLE PRECISION AS INVESMENT,
    (T2.STIKER_PRICE::DOUBLE PRECISION - T1.PRICE) * T1.SHARES::DOUBLE PRECISION AS PROFIT,
    CURRENT_DATE  - TRANS_DATE  AS DAYS_IN
FROM DF_CANTOR  T1
LEFT JOIN DF_KPI T2 ON T1.TICKER = T2.TICKER
WHERE ACTIVE_FLAG = 1
ORDER BY  T1.TRANS_DATE;



---DF_PORFOLIO_VIEW

DROP TABLE IF EXISTS DF_PORFOLIO_VIEW;
CREATE TABLE DF_PORFOLIO_VIEW AS  
SELECT  
    
    T1.PORFOLIO
    ,T1.TICKER
     , 0 AS SELL_FLAG 
     , ((T3.STIKER_PRICE::DOUBLE PRECISION - T2.CLOSE_ADJ_PRICE) / ( (T3.STIKER_PRICE )::DOUBLE PRECISION)::DOUBLE PRECISION)::NUMERIC(10,6) AS PROFIT_PERC
    ,T2.CLOSE_ADJ_PRICE AS  TRANS_PRICE
    ,T3.STIKER_PRICE AS ACTUAL_PRICE 
    ,T3. Y_PRICE_1Y_EST  
    ,T3.REC_RANK
    ,T3.BS_FLAG
    ,T3.bs_flag_trend_days_in
    ,T3.SCORE_VALUATION
    ,T3.GOODPRICE_R1_FLAG
     ,T3.NAME
    ,T1.TRANS_DATE
    ,CURRENT_DATE  - T1.TRANS_DATE AS DAYS_IN
   
FROM DF_PORFOLIO T1
LEFT JOIN   PUBLIC.DF_BUY_SELL_FLAG  T2 ON T1.TICKER =T2.TICKER  AND T2.PRICE_DATE = (
                                                                                        SELECT MAX (T2A.PRICE_DATE)
                                                                                        FROM  PUBLIC.DF_BUY_SELL_FLAG  T2A
                                                                                        WHERE T2A.TICKER =T2.TICKER 
                                                                                        AND  T2A.PRICE_DATE <= T1.TRANS_DATE )
                                                                                        
LEFT JOIN   PUBLIC.DF_KPI_S  T3 ON T1.TICKER =T3.TICKER   
ORDER BY  T1.PORFOLIO , T1.TRANS_DATE ;

----CLOSE IN GREENS 
UPDATE  DF_PORFOLIO_VIEW SET SELL_FLAG = 1   WHERE PROFIT_PERC >=.1;
UPDATE  DF_PORFOLIO_VIEW SET SELL_FLAG = 1   WHERE PROFIT_PERC >=.03 AND DAYS_IN < 4  AND UPPER (PORFOLIO) = 'ETORO';
UPDATE  DF_PORFOLIO_VIEW SET SELL_FLAG = 1   WHERE PROFIT_PERC >.0 AND DAYS_IN > 100  AND BS_FLAG LIKE '%BUY%' ;
UPDATE  DF_PORFOLIO_VIEW SET SELL_FLAG = 1   WHERE PROFIT_PERC >.05 AND BS_FLAG LIKE '%BUY%'  ;

----CLOSE IN REDS
UPDATE  DF_PORFOLIO_VIEW SET SELL_FLAG = -1   WHERE  PROFIT_PERC <0 AND  DAYS_IN > 100  AND GOODPRICE_R1_FLAG <0;


 

END
$procedure$
