
CREATE OR REPLACE PROCEDURE public.run_etl_fundamentals_tickers_update(
	)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN

DELETE  FROM TICKERS_TEST;
INSERT INTO  TICKERS_TEST

SELECT TICKER
FROM C_HISTORICS_CONTROL
WHERE TICKER IN (
				SELECT TICKER
				FROM DF_FUNDAMENTALS
				WHERE BIG5_TOTAL >= 1
)
AND FUNDAMENTALS_YEAR_MAX< EXTRACT(YEAR FROM CURRENT_DATE)-1 ;



END
$BODY$;
