

CREATE OR REPLACE PROCEDURE ut_fundamentals_control(  )
LANGUAGE 'plpgsql'
AS $PROCEDURE$
BEGIN



DROP TABLE IF EXISTS C_HISTORICS_CONTROL;

CREATE TABLE C_HISTORICS_CONTROL AS (

    SELECT 
           TICKER
        ,CAST ( 0 AS 	INT	) AS 	FUNDAMENTALS_FLAG
        ,CAST ( 0 AS 	int	) AS 	FUNDAMENTAL_ALL_CHECK
        ,CAST ( 0 AS 	int	) AS 	FUNDAMENTALS_YEAR_MIN
        ,CAST ( 0 AS 	int	) AS 	FUNDAMENTALS_YEAR_MAX
        ,CAST ( 0 AS 	int	) AS 	FUNDAMENTALS_YEAR_NO
        ,CAST ( 0 AS 	INT	) AS 	QUOTE_FLAG
        ,CAST ( NULL AS 	DATE	) AS 	QUOTE_DATE_MIN
        ,CAST ( NULL AS 	DATE	) AS 	QUOTE_DATE_MAX
        ,CAST ( 0 AS 	INT	) AS 	STATS_FLAG
        ,CAST ( NULL AS 	DATE	) AS 	STATS_DATE_MIN
        ,CAST ( NULL AS 	DATE	) AS 	STATS_DATE_MAX
        ,CAST ( 0 AS 	INT	) AS 	ZACKS_FLAG
        ,CAST ( NULL AS 	DATE	) AS 	ZACKS_DATE_MIN
        ,CAST ( NULL AS 	DATE	) AS 	ZACKS_DATE_MAX
    ,CAST ( 0 AS 	INT	) AS 	YAHOO_FLAG
        ,CAST ( NULL AS 	DATE	) AS 	YAHOO_DATE_MIN
        ,CAST ( NULL AS 	DATE	) AS 	YAHOO_DATE_MAX

    FROM  DF_H_TICKER_NAME

) ;


--C_HISTORICS_CONTROL
UPDATE C_HISTORICS_CONTROL  AS T1 
SET 
FUNDAMENTALS_FLAG=1
,FUNDAMENTAL_ALL_CHECK=t2.FUNDAMENTAL_ALL_CHECK
,FUNDAMENTALS_YEAR_MIN=t2.FUNDAMENTALS_YEAR_MIN
,FUNDAMENTALS_YEAR_MAX=t2.FUNDAMENTALS_YEAR_MAX
,FUNDAMENTALS_YEAR_NO=t2.FUNDAMENTALS_YEAR_NO
FROM  (

SELECT 
    TICKER
    , MIN (YEAR ) AS FUNDAMENTALS_YEAR_MIN
    , MAX (YEAR ) AS FUNDAMENTALS_YEAR_MAX
   	,count (distinct year ) as FUNDAMENTALS_YEAR_NO
    ,CASE WHEN SUM(DISTINCT FUNDAMENTAL_ID) = 148 THEN 1 ELSE  0  END  AS FUNDAMENTAL_ALL_CHECK 
FROM PUBLIC.FUNDAMENTALS_HISTORIC 
GROUP BY TICKER

) AS T2
WHERE ( T1.TICKER=T2.TICKER );





--DF_QUOTE_H
UPDATE C_HISTORICS_CONTROL  AS T1 
SET 
QUOTE_FLAG=1
,QUOTE_DATE_MIN=t2.QUOTE_DATE_MIN
,QUOTE_DATE_MAX=t2.QUOTE_DATE_MAX
FROM  (


SELECT 
    TICKER
    , MIN (LOAD_DATE ) AS QUOTE_DATE_MIN
    , MAX (LOAD_DATE ) AS QUOTE_DATE_MAX

FROM PUBLIC.DF_QUOTE_H 
GROUP BY TICKER

) AS T2
WHERE ( T1.TICKER=T2.TICKER );



--DF_STATS_H

UPDATE C_HISTORICS_CONTROL  AS T1 
SET 
STATS_FLAG=1
,STATS_DATE_MIN=t2.STATS_DATE_MIN
,STATS_DATE_MAX=t2.STATS_DATE_MAX
FROM  (


SELECT 
    TICKER
    , MIN (LOAD_DATE ) AS STATS_DATE_MIN
    , MAX (LOAD_DATE ) AS STATS_DATE_MAX

FROM PUBLIC.DF_STATS_H 
GROUP BY TICKER

) AS T2
WHERE ( T1.TICKER=T2.TICKER );



--DF_H_ZACKS_INDICATORS
UPDATE C_HISTORICS_CONTROL  AS T1 
SET 
ZACKS_FLAG=1
,ZACKS_DATE_MIN=t2.ZACKS_DATE_MIN
,ZACKS_DATE_MAX=t2.ZACKS_DATE_MAX
FROM  (


SELECT 
    TICKER
    , MIN (LOAD_DATE ) AS ZACKS_DATE_MIN
    , MAX (LOAD_DATE ) AS ZACKS_DATE_MAX

FROM PUBLIC.DF_H_ZACKS_INDICATORS  
GROUP BY TICKER

) AS T2
WHERE ( T1.TICKER=T2.TICKER );



--DF_H_ZACKS_INDICATORS
UPDATE C_HISTORICS_CONTROL  AS T1 
SET 
YAHOO_FLAG=1
,YAHOO_DATE_MIN=t2.YAHOO_DATE_MIN
,YAHOO_DATE_MAX=t2.YAHOO_DATE_MAX
FROM  (


SELECT 
    TICKER
    , MIN (LOAD_DATE ) AS YAHOO_DATE_MIN
    , MAX (LOAD_DATE ) AS YAHOO_DATE_MAX

FROM PUBLIC.DF_YAHOO_RECOMMENDATIONS  
GROUP BY TICKER

) AS T2
WHERE ( T1.TICKER=T2.TICKER );




  END
$PROCEDURE$
